Attitude model
aidotse/PASEOS pull request #194
Opened 2024-01-10 11:52 UTC by Mr-Medina

# Description
An attitude model is added, simulating the evolution of a spacecraft actor attitude through time with external attitude disturbances. User can specify initial contitions: spacecraft attitude (being roll, pitch and yaw angles) and angular velocity. 
Disturbance torque calulations are not implemented yet but framework is present for later implementation.

Reference frame transfer file is also made in utils, able to switch between Earth-centered inertial, roll pitch yaw (based on nadir & along track directions) and body fixed frames. Also used for vector rotations in reference frames and extracting roll, pitch, and yaw angles between frames. 
Summary of changes

* attitude model added
* reference frame transformation functions added
* disturbance calculations framework added

## Resolved Issues

- [ ] fixes #193 

## How Has This Been Tested?
I made a file which plots the pointing vector in the spacecraft trajectory using matplotlib. I was not sure if I needed to add this in the PR. Please refer to my fork to file "test_attitude_plotting.py" for visual reference.
Further testing methods will be added after feedback is received.

2024-01-11 08:08 UTC, gomezzz commented
@Mr-Medina Should we have a look and give you some feedback? :) 

You can request a review in the top right with

![grafik](https://github.com/aidotse/PASEOS/assets/2656685/57d53791-a2ad-4e7c-bee5-701f6953a311)

2024-01-11 18:57 UTC, GabrieleMeoni requested changes
At a first glance, it looks good. We can have a dedicated discussion later on. I would wait for  the geometric model PR to be updated as requested. This code needs also to capitalize on that PR.

2024-01-11 18:57 UTC, GabrieleMeoni commented on paseos/attitude/attitude_model.py
> +    def update_attitude(self, dt):
Make sure this function is always called inside PASEOS main loop to be sure the variables will be updated all at the same time: https://github.com/aidotse/PASEOS/blob/e5bb071b4ee2988c2765497aa8fe3d0f6eacb655/paseos/paseos.py#L123

2024-01-11 21:45 UTC, Mr-Medina commented on paseos/attitude/attitude_model.py
> +        T = np.array([0.0, 0.0, 0.0])
Yes, the T vector will be expressed in the body frame

2024-01-11 21:52 UTC, Mr-Medina commented on paseos/attitude/attitude_model.py
> +        # a = angular acceleration, I = inertia matrix, T = torque vector, w = angular velocity
done!

2024-01-19 15:17 UTC, Moanalengkeek approved these changes

2024-01-19 15:18 UTC, merged