Visual implementation follow up
aidotse/PASEOS pull request #39
Opened 2022-11-14 14:37 UTC by gomezzz

# Description

Summary of changes

* Changed API to simplify user interaction
* Fixed problems on win / linux
* Some minor restyling
* Refactoring

## Resolved Issues

N/A

## How Has This Been Tested?

- example jupyter notebook
- ran tests

## Related Pull Requests

- #27

2022-11-14 20:20 UTC, johanos1 requested changes

2022-11-15 12:20 UTC, gomezzz commented on paseos/visualization/space_animation.py
> +        self.date_label.set_text(self._local_actor.local_time)
Can you post a stacktrace? I suspect the error occurs inside pykep as this is a C++ error message if I am googling right. Ideally we open an issue on pykep and I will readd the try/catch

2022-11-15 13:53 UTC, johanos1 commented on paseos/visualization/space_animation.py
> +        self.date_label.set_text(self._local_actor.local_time)
I doubt this is enough, but using traceback.print_exc() I get:

```
> Traceback (most recent call last):
>   File "/Users/johanostman/Dropbox/Machine Learning/Decentralized AI/Code/PASEOS/examples/../paseos/visualization/space_animation.py", line 371, in update
>     self.date_label.set_text(self._local_actor.local_time)
>   File "/opt/homebrew/Caskroom/miniforge/base/envs/paseos/lib/python3.8/site-packages/matplotlib/text.py", line 1242, in set_text
>     self._text = str(s)
> RuntimeError: bad lexical cast: source type value could not be interpreted as target
```

2022-11-15 18:59 UTC, johanos1 approved these changes

2022-11-16 10:05 UTC, merged