Warning user if constraint function doesn't return a value
aidotse/PASEOS pull request #70
Opened 2022-12-12 16:26 UTC by gomezzz

# Description

Added error in log like this

![image](https://user-images.githubusercontent.com/2656685/207097863-5c91bfec-0e2b-4aaa-bf03-75f7a92da7f4.png)

@GabrieleMeoni I could not find a way to raise an exception inside the async functions. Instead I display an error like above, good enough for now I think?

The original problem of the termination function running twice, I think, was already solved before?

## Resolved Issues

- [x] fixes #44 

## How Has This Been Tested?

Specific test

## Related Pull Requests

N/A

2022-12-17 13:58 UTC, GabrieleMeoni requested changes
I don't get any warning. I used the notebook attached to test it. What am I doing wrong? 
[notebook.zip](https://github.com/aidotse/PASEOS/files/10251848/notebook.zip)

2022-12-19 08:02 UTC, gomezzz commented
> I don't get any warning. I used the notebook attached to test it. What am I doing wrong? [notebook.zip](https://github.com/aidotse/PASEOS/files/10251848/notebook.zip)

You activity is too short. The constraint is never checked because it runs less than a second. If I increase the sleep in the activity to two seconds, it works for me. Can you check?

2022-12-19 08:44 UTC, GabrieleMeoni approved these changes

2022-12-19 08:46 UTC, GabrieleMeoni commented
Yes, tested and works as expected for an activity lasting 2 seconds. Should we add an issue to notify the user about this problem? (You set a constraint function but the activity is too short and will never get tested.)? @gomezzz

2022-12-19 10:15 UTC, gomezzz commented
> Yes, tested and works as expected for an activity lasting 2 seconds. Should we add an issue to notify the user about this problem? (You set a constraint function but the activity is too short and will never get tested.)? @gomezzz

@GabrieleMeoni Hm, depends, maybe we should be checking the constraint once before we start the activity? If so, then yes

2022-12-19 10:17 UTC, merged