Constellation example
aidotse/PASEOS pull request #92
Opened 2022-12-26 10:53 UTC by gomezzz

# Description

TBD

## Resolved Issues

- [ ] fixes #91

## How Has This Been Tested?

TBD

## Related Pull Requests

- #90 #89

2023-01-04 18:09 UTC, johanos1 requested changes
Very nice notebook! All my comments are minor

2023-01-04 18:09 UTC, johanos1 commented on examples/Constellation_example/constellation.md
> +            values = convert_known_actors_to_categorical(instance.monitor[item])
The name of this function does not seem accurate.
```suggestion
            values = get_known_actor_comms_status(instance.monitor[item])
```

2023-01-04 18:09 UTC, johanos1 commented on examples/Constellation_example/constellation.md
> +# create stacked bar chart for monthly temperatures
this comment is not correct

2023-01-05 09:36 UTC, gomezzz commented on .gitignore
> +thermal_test.csv
> why do we write csv files in the test?
I wrote them to check writing works and to have a look at the values. 

> Would it be a good idea to read them in, verify that they write what we expect, and then delete instead?
We can but I already verify (some of the) values in the tests, so this only test the I/O. If we want this, would suggest to add #1

2023-01-05 09:43 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +In addition to PASEOS's requirements this notebook uses seaborn and pandas. `conda install seaborn` or `pip install seaborn` will get it. (installing seaborn will get pandas too)
mentioning both now

2023-01-05 09:44 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +    [32m15:40:55[0m|PASEOS-[34mDEBUG[0m| [34m[1mSetting LogLevel to DEBUG[0m
This always happens because our default warning level is DEBUG, it is printed on PASEOS import. If we want to change, should be a dedicated issue :v:

2023-01-05 09:46 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +simulation_time = 4.0 * 3600 # one day in seconds
I actually changed it to 8 hours now because after a few hours it is stable anyways

2023-01-05 09:48 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +timestep = 600 # refresh interval deciding which activity to perform
changed, clearer now?

2023-01-05 09:49 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +            constraint_function=eval_constraint
Added a comment, better?

2023-01-05 10:50 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +gs_actor = ActorBuilder.get_actor_scaffold(name="gs_1",actor_type=GroundstationActor, epoch=t0)
We are not really modeling comms here, so not necessary

2023-01-05 10:52 UTC, gomezzz commented on examples/Constellation_example/constellation.md
> +        return 100.0,"Processing"
(added comment in the notebook, sorry saw this comment only after review somehow)

2023-01-06 11:11 UTC, johanos1 approved these changes

2023-01-09 10:50 UTC, merged